name: jobs example
on: 
  push:
    branches:
      - main

jobs:
  job_id_1:
    name: number 1 added to file
    runs-on: ubuntu-latest
    steps:
      - name: file created 
        run: sudo touch mysum.txt
      - name: number added to file
        run: sudo sh -c "echo 5 > mysum.txt" 

      - name: upload file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: myfile
          path: mysum.txt

  job_id_2:
    needs: job_id_1
    name: number 2 added to file
    runs-on: ubuntu-latest
    steps:
      - name: download file from job 1
        uses: actions/download-artifact@v4
        with:
          name: myfile
          path: .
      - name: dispaly structure
        run: sudo ls -r
        

  job_id_3:
    needs: job_id_2
    name: myjob3
    runs-on: ubuntu-latest
    steps:
      - name: job 3 step 1 runs
        run: sleep 3 | echo "job 3 running now"

  job_id_4:
    needs: job_id_3
    name: myjob4
    runs-on: ubuntu-latest
    steps: 
      - name: job 4 step 1 runs
        run: sleep 20 |  echo "job 4 is running now"