name: jobs example
on: 
  push:
    branches:
      - main

jobs:
  job_id_1:
    name: number 1 added to file
    runs-on: ubuntu-latest
    steps:
      - name: file created 
        run: sudo touch mysum1.txt
      - name: number added to file
        run: sudo sh -c "echo 5 > ./mysum1.txt" 

      - name: current file ls
        run: ls -la

      - name: upload file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: myfile1
          path: .

  job_id_2:
    needs: job_id_1
    name: number 2 added to file
    runs-on: ubuntu-latest
    steps:
      - name: create file 2
        run: sudo touch mysum2.txt

      - name: dispaly structure
        run: sudo ls -la /tmp
      
      - name: add file 2
        run: sudo sh -c "echo 7 > /tmp/mysum2.txt"
      
      - name: upload file 2 as artifact
        uses: actions/upload-artifact@v4
        with:
          name: myfile2
          path: /tmp

        

  job_id_3:
    needs: [job_id_1,job_id_2]
    name: download and add both file
    runs-on: ubuntu-latest
    steps:
      - name: download  file1
        uses: actions/download-artifact@v4
        with:
          name: myfile1
          path: /tmp

      - name: download  file2
        uses: actions/download-artifact@v4
        with:
          name: myfile2
          path: /tmp

      - name: display structure
        run: sudo ls -la /tmp

      - name: add both files number
        run: |
           sum=$(( $(cat /tmp/mysum1.txt) + $(cat /tmp/mysum2.txt) ))
           echo $sum
           echo "$sum" > /tmp/mysum3.txt

      - name: upload sum as artifact
        uses: actions/upload-artifact@v4
        with:
          name: mysum
          path: /tmp


          

  job_id_4:
    needs: job_id_3
    name: display sum
    runs-on: ubuntu-latest
    steps: 

      - name: download sum artifact file
        uses: actions/download-artifact@v4
        with: 
          name: mysum
          path: /tmp

      - name: display sum
        run: cat /tmp/mysum3.txt