name: jobs example
on: 
  push:
    branches:
      - main

jobs:
  job_id_1:
    name: number 1 added to file
    runs-on: ubuntu-latest
    steps:
      - name: file created 
        run: sudo touch mysum1.txt
      - name: number added to file
        run: sudo sh -c "echo 5 > mysum1.txt" 

      - name: upload file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: myfile1
          path: mysum1.txt

  job_id_2:
    #needs: job_id_1
    name: number 2 added to file
    runs-on: ubuntu-latest
    steps:
      - name: create file 2
        run: sudo touch mysum2.txt

      - name: dispaly structure
        run: sudo ls -r
      
      - name: add file 2
        run: sudo sh -c "echo 7 > mysum2.txt"
      
      - name: upload file 2 as artifact
        uses: actions/upload-artifact@v4
        with:
          name: myfile2
          path: mysum2.txt

        

  job_id_3:
    #needs: job_id_2
    name: download and add both file
    runs-on: ubuntu-latest
    steps:
      - name: download  file1
        uses: actions/download-artifact@v4
        with:
          name: myfile1
          path: mysum1.txt

      - name: download  file2
        uses: actions/download-artifact@v4
        with:
          name: myfile2
          path: mysum2.txt

      - name: add both files number
        run: |
           sum=$(( $(cat mysum1.txt) + $(cat mysum2.txt) ))
           echo "$sum" > mysum3.txt

      - name: upload sum as artifact
        uses: actions/upload-artifact@v4
        with:
          name: mysum
          path: mysum3.txt


          

  job_id_4:
    #needs: job_id_3
    name: display sum
    runs-on: ubuntu-latest
    steps: 
      - name: download sum artifact file
        uses: actions/download-artifact@v4
        with: 
          name: mysum
          path: .

      - name: display sum
        run: cat mysum3.txt