name: jobs example
on: 
  push:
    branches:
      - main
env:
  MYNAME: rakesh
 

jobs:
  job_id_1:
    name: number 1 added to file
    runs-on: ubuntu-latest
    steps:
      - name: file created 
        run: sudo touch mysum1.txt
      - name: number added to file
        run: sudo sh -c "echo 5 > ./mysum1.txt" 

      - name: current file ls
        run: ls -la

      - name: upload file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: myfile1
          path: .

  job_id_2:
    needs: job_id_1
    name: number 2 added to file
    runs-on: ubuntu-latest
    steps:
      - name: create file 2
        run: sudo touch mysum2.txt

      - name: dispaly structure
        run: sudo ls -la 
      
      - name: add file 2
        run: sudo sh -c "echo 7 > ./mysum2.txt"
      
      - name: upload file 2 as artifact
        uses: actions/upload-artifact@v4
        with:
          name: myfile2
          path: .

        

  job_id_3:
    needs: [job_id_1,job_id_2]
    name: download and add both file
    runs-on: ubuntu-latest
    steps:
      - name: download  file1
        uses: actions/download-artifact@v4
        with:
          name: myfile1
          path: .

      - name: download  file2
        uses: actions/download-artifact@v4
        with:
          name: myfile2
          path: .

      - name: display structure
        run: sudo ls -la 

      - name: add both files number
        run: |
           sum=$(( $(cat ./mysum1.txt) + $(cat ./mysum2.txt) ))
           echo $sum
           echo "$sum" > ./mysum3.txt

      - name: upload sum as artifact
        uses: actions/upload-artifact@v4
        with:
          name: mysum
          path: .


          

  job_id_4:
    needs: job_id_3
    name: display sum
    runs-on: ubuntu-latest
    steps: 

      - name: download sum artifact file
        uses: actions/download-artifact@v4
        with: 
          name: mysum
          path: .

      - name: display sum
        run: cat ./mysum3.txt

  job_id_5:
    name: run script from workflow
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts
    steps:
      - name: check out repo for fetching script to runner
        uses: actions/checkout@v4

      - name: print current directory
        run: pwd
      - name: print dir structure
        run: ls -la

      - name: run the script
        run: chmod +x ./myscript.sh
        env:
          city: limbdi #only applies to this step

