name: jobs example
on: 
  push:
    branches:
      - main

jobs:
  job_id_1:
    name: myjob1
    runs-on: ubuntu-latest
    steps:
      - name: job 1 step 1 runs
        run: sleep 5 | echo "job 1 runs now" 
  job_id_2:
    needs: job_id_1
    name: myjob2
    runs-on: ubuntu-latest
    steps:
      - name: job 2 step 1 runs
        run: sleep 5 | echo "job 2 is running now"

  job_id_3:
    needs: job_id_2
    name: myjob3
    runs-on: ubuntu-latest
    steps:
      - name: job 3 step 1 runs
        run: sleep 3 | echo "job 3 running now"

  job_id_4:
    needs: job_id_3
    name: myjob4
    runs-on: ubuntu-latest
    steps: 
      - name: job 4 step 1 runs
        run: sleep 20 |  echo "job 4 is running now"